// Generated by gencpp from file agitr/WordCount.msg
// DO NOT EDIT!


#ifndef AGITR_MESSAGE_WORDCOUNT_H
#define AGITR_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <agitr/WordCountRequest.h>
#include <agitr/WordCountResponse.h>


namespace agitr
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace agitr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agitr::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::agitr::WordCount&) { return value(); }
};

template<>
struct DataType< ::agitr::WordCount > {
  static const char* value()
  {
    return "agitr/WordCount";
  }

  static const char* value(const ::agitr::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::agitr::WordCountRequest> should match 
// service_traits::MD5Sum< ::agitr::WordCount > 
template<>
struct MD5Sum< ::agitr::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agitr::WordCount >::value();
  }
  static const char* value(const ::agitr::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agitr::WordCountRequest> should match 
// service_traits::DataType< ::agitr::WordCount > 
template<>
struct DataType< ::agitr::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::agitr::WordCount >::value();
  }
  static const char* value(const ::agitr::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agitr::WordCountResponse> should match 
// service_traits::MD5Sum< ::agitr::WordCount > 
template<>
struct MD5Sum< ::agitr::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agitr::WordCount >::value();
  }
  static const char* value(const ::agitr::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agitr::WordCountResponse> should match 
// service_traits::DataType< ::agitr::WordCount > 
template<>
struct DataType< ::agitr::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::agitr::WordCount >::value();
  }
  static const char* value(const ::agitr::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGITR_MESSAGE_WORDCOUNT_H
